### ISSUE TITLE
Request to contribute

### ISSUE THREAD

**Issue by aviditi-will** [lweller/xray-cucumber-intellij#1]
Hi @lweller,

I'm interested in contributing to this repo to add in the test upload functionality and noticed you had already started a new branch with a portion of the work completed.

Would you be open to allowing me to contribute to this plugin? I am currently unable to create a pull request.

Could you provide some insight to what is remaining that needs to be done in the branch you have created.

Thanks!
Will

**Comment by lweller** [comment]
Hi @aviditi-will,

Thank you for your request. Yes I did already some work to implement a full round trip (Xray -> IntelliJ -> Xray) for Cucumber feature files. But I had to put it aside due to other priorities by now.

Dou you have an concrete idea about what you wan to contribute?

Best regards

Lucien

**Comment by aviditi-will** [comment]
My plan is to finish up the new feature that you started to upload test files back to the Jira server.

That's the only thing missing from this plugin or me - otherwise it's great!

I wanted to reach out before I spent a bunch of time reviewing your code and submitting a PR.
